In [2]:
import pandas as pd

df = pd.read_csv("Hospital Billing - Event Log.csv")

df.head(20)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,lifecycle:transition,isCancelled,diagnosis,caseType,...,flagA,state,closeCode,actRed,actOrange,flagC,msgCount,version,msgType,msgCode
0,A,NEW,ResA,2012-12-16 19:33:10.000,Variant 3,3,complete,False,A,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,FIN,NaN,2013-12-15 19:00:37.000,Variant 3,3,complete,NaN,NaN,NaN,...,NaN,Closed,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,RELEASE,NaN,2013-12-16 03:53:38.000,Variant 3,3,complete,NaN,NaN,NaN,...,NaN,Released,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,CODE OK,NaN,2013-12-17 12:56:29.000,Variant 3,3,complete,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,False,0.0,A,NaN,NaN
4,A,BILLED,ResB,2013-12-19 03:44:31.000,Variant 3,3,complete,NaN,NaN,NaN,...,NaN,Billed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,B,NEW,ResA,2012-12-16 19:33:50.000,Variant 4,4,complete,False,B,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,B,DELETE,ResC,2013-10-19 12:37:05.000,Variant 4,4,complete,True,NaN,NaN,...,NaN,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,C,NEW,ResA,2013-01-13 21:04:24.000,Variant 130,130,complete,False,C,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,C,FIN,NaN,2013-04-17 19:59:43.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,Closed,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,C,RELEASE,NaN,2013-04-18 02:30:35.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,Released,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,C,CODE OK,NaN,2013-04-21 01:55:12.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,NaN,NaN,False,False,False,0.0,B,NaN,NaN
11,C,REOPEN,ResD,2013-05-01 14:41:32.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,C,CHANGE DIAGN,NaN,2013-05-01 14:41:54.000,Variant 130,130,complete,NaN,D,NaN,...,NaN,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,C,FIN,ResA,2013-05-02 20:33:39.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,Closed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,C,RELEASE,NaN,2013-05-03 04:03:17.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,Released,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,C,CODE OK,NaN,2013-05-03 05:21:24.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,C,BILLED,ResB,2013-05-23 07:32:15.000,Variant 130,130,complete,NaN,NaN,NaN,...,NaN,Billed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,D,NEW,ResA,2013-01-16 21:05:37.000,Variant 3,3,complete,False,E,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,D,FIN,NaN,2014-01-15 20:15:25.000,Variant 3,3,complete,NaN,NaN,NaN,...,NaN,Closed,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,D,RELEASE,NaN,2014-01-16 03:50:37.000,Variant 3,3,complete,NaN,NaN,NaN,...,NaN,Released,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns

Index(['Case ID', 'Activity', 'Resource', 'Complete Timestamp', 'Variant',
       'Variant index', 'lifecycle:transition', 'isCancelled', 'diagnosis',
       'caseType', 'speciality', 'blocked', 'isClosed', 'flagD', 'flagB',
       'flagA', 'state', 'closeCode', 'actRed', 'actOrange', 'flagC',
       'msgCount', 'version', 'msgType', 'msgCode'],
      dtype='str')

In [4]:
df["Activity"].unique()

<StringArray>
[         'NEW',          'FIN',      'RELEASE',      'CODE OK',
       'BILLED',       'DELETE',       'REOPEN', 'CHANGE DIAGN',
       'STORNO',       'REJECT',     'CODE NOK',   'SET STATUS',
   'CHANGE END',       'MANUAL',     'JOIN-PAT',   'CODE ERROR',
   'ZDBC_BEHAN',        'EMPTY']
Length: 18, dtype: str

### Variante 5: NEW -> FIN

In [7]:
df_v5 = df[df["Variant index"] == 5]
df_v5.head(20)

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,lifecycle:transition,isCancelled,diagnosis,caseType,...,flagA,state,closeCode,actRed,actOrange,flagC,msgCount,version,msgType,msgCode
311,IB,NEW,ResA,2013-01-22 03:17:54.000,Variant 5,5,complete,False,AB,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,IB,FIN,NaN,2014-01-21 02:45:13.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
702,VD,NEW,ResIA,2013-01-14 10:46:32.000,Variant 5,5,complete,False,HA,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
703,VD,FIN,ResA,2014-01-18 00:32:16.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1288,EI,NEW,ResA,2013-01-14 21:19:32.000,Variant 5,5,complete,False,ZE,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1289,EI,FIN,NaN,2014-01-13 22:01:46.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1301,HI,NEW,ResA,2013-01-17 21:41:41.000,Variant 5,5,complete,False,LC,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1302,HI,FIN,NaN,2014-01-16 22:01:57.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1429,OJ,NEW,ResA,2012-12-19 04:23:43.000,Variant 5,5,complete,False,G,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1430,OJ,FIN,NaN,2013-12-26 20:00:55.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1972,KN,NEW,ResA,2012-12-20 19:31:28.000,Variant 5,5,complete,False,H,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1973,KN,FIN,NaN,2013-12-20 19:00:42.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005,RN,NEW,ResA,2013-01-17 00:24:28.000,Variant 5,5,complete,False,CH,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006,RN,FIN,NaN,2014-01-16 22:46:32.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2516,VR,NEW,ResOB,2012-12-29 17:54:47.000,Variant 5,5,complete,False,UB,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2517,VR,FIN,ResA,2013-12-29 20:59:28.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2739,IT,NEW,ResA,2013-01-22 21:28:41.000,Variant 5,5,complete,False,CF,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2740,IT,FIN,NaN,2014-01-25 20:02:49.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2753,MT,NEW,ResA,2012-12-21 21:32:05.000,Variant 5,5,complete,False,FB,A,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2754,MT,FIN,NaN,2013-12-24 20:03:00.000,Variant 5,5,complete,NaN,NaN,NaN,...,NaN,Empty,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_v5.describe()

       Variant index  msgCount
count         7016.0       0.0
mean             5.0       NaN
std              0.0       NaN
min              5.0       NaN
25%              5.0       NaN
50%              5.0       NaN
75%              5.0       NaN
max              5.0       NaN

In [11]:
df_v5.nunique()

Case ID                 3508
Activity                   2
Resource                 277
Complete Timestamp      7009
Variant                    1
Variant index              1
lifecycle:transition       1
isCancelled                1
diagnosis                476
caseType                   2
speciality                20
blocked                    1
isClosed                   1
flagD                      2
flagB                      1
flagA                      1
state                      3
closeCode                  5
actRed                     0
actOrange                  0
flagC                      0
msgCount                   0
version                    0
msgType                    0
msgCode                    0
dtype: int64

### Variante 2: NEW

In [13]:
df_v2 = df[df["Variant index"] == 2]
df_v2.head()

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,lifecycle:transition,isCancelled,diagnosis,caseType,...,flagA,state,closeCode,actRed,actOrange,flagC,msgCount,version,msgType,msgCode
119,U,NEW,ResBA,2013-01-13 12:47:26.000,Variant 2,2,complete,False,NaN,C,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,V,NEW,ResBA,2012-12-20 12:58:01.000,Variant 2,2,complete,False,NaN,C,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,NEW,ResJA,2012-12-14 22:52:38.000,Variant 2,2,complete,False,NaN,C,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,ZD,NEW,ResNC,2013-01-21 14:30:16.000,Variant 2,2,complete,False,NaN,C,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,AE,NEW,ResNC,2012-12-22 14:30:16.000,Variant 2,2,complete,False,NaN,C,...,False,In progress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_v2.nunique()

Case ID                 22372
Activity                    1
Resource                   21
Complete Timestamp      20584
Variant                     1
Variant index               1
lifecycle:transition        1
isCancelled                 1
diagnosis                  68
caseType                    9
speciality                 19
blocked                     1
isClosed                    2
flagD                       2
flagB                       1
flagA                       1
state                       1
closeCode                   0
actRed                      0
actOrange                   0
flagC                       0
msgCount                    0
version                     0
msgType                     0
msgCode                     0
dtype: int64

In [16]:
# Variante 2 löschen und CSV speichern
variant_2_cases = df[df["Variant index"] == 2]["Case ID"].unique()
df_clean = df[~df["Case ID"].isin(variant_2_cases)].copy()
print("Original Cases:", df["Case ID"].nunique())
print("Cleaned Cases:", df_clean["Case ID"].nunique())
print("Removed Cases:", len(variant_2_cases))

Original Cases: 99999
Cleaned Cases: 77627
Removed Cases: 22373

In [17]:
df_clean.to_csv("Hospital Billing - Event Log_cleaned.csv", index=False)